---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBqcmkTk/VP73eHeXx5ENLZYj2T7/cZgNdANS8ZJGJuzdzMGWZNTflQLC24M6ppILi7Az+imdAe45krXj6c9HoMDQhGCBXYaPsB+QhdudM/QTnAU2HTcrr+EKQxvv8LfZGGl/glPa7fBS+GDp+F/wNpUnsq1A6Dp6zm60v91HyjYJmJma8dWvGxe+FlByllO5HIwcx7VixDtAsNiz20yKqikDs6sFi11ipECUOF+OSiz+7oGg1x2Ron4YZ1lfTnjVaQD+r7rLnoshGcW9FJ3ZyQWMD66rQmE06pjNKLQa5AX2KGZhrF13d59x1MkKZZi54oYo5QcjRw4OX66fyp89ohk/9uWHiJMFvd/bn+rigAVYgUeJ4ofa7WLjHulGVjh1PgIlCPX2BluMMZdnQd+6Xcarvu6cEPCUEM/G4MtkdaDno1NzFFA9xJvNevcsPH1cOhDKEKOTvn/AeNb+pML7VY1QfTkq9bfJsekwsecBwi14LlYNxd+Uqgc42LOfScppBS8Gi4BnbEVApCi9FP5y+d+UcPrQ23+CP7fyigospPXKc+xcvFEPsQIw99qcbwTJXac4fTzWPz3HwIip4VxomZpE7H6Od5OBCL4tsYisfShkvrgI+siaOBqyKDQm94oh16O+4aPh1z+s1+3szMXN1TS6OWoHtVoXPYCnz7/pkn3+ve66Hgc5RuccH8URoVfhhvNmufKMwdD3bfJwgVFKYSEBeQPlcUWzn2kbDzXJNDdConBR0PtliasW2f0g==
    admin-user: AgB7pBa/5YgEeBELqXq6zjnRNvqhJS3zhZ7AW8bRqa/00oPFzeklA/kT7lPyVxGXkGtLpgL7u5hgh2VUN0Zv4sqipO00T70rRU77SD+lm4DqnJH2dpyiNZMmdio/Y/QOsVd+ss1fDnm7TFdtv69dRtsT9grtqpO1/8ssILEUk9AGElr7a8a94ppm1Oq9XlMMQZfCEgcANYSBjHPAsuPA1gyAURpXWLuYW6A7PyWx8RVXbIMBvsN9QTjgxllJrJ5+pSSZA/Yh6uIUPHo2P9ETbTHTOpmvnqzifsad8Ta6mbiwoqXPzhfrCQvBLnVnAK2ybWjihAWeoljdSTSS4V/YPQI8ZxodU6+QX2ya7CE8zsVlkVISXlqtol4E1+VqbK23cn0BGgl1n0tGhMkavtGjxQLcOjxN14wG4Iqb5sXQpwVR0gbBvHpenOyMgLCNz+pkAoGoNi/LAYPEIdbpj25r2zyT/8mboMoYT8zWxMQ0ktHh5sFIoPSUCrRDLTimWa0Uiu1nbH0w0hbms13cvCQhKEYdakAq40V3rRWUCa8vHfTeKMxqmWAPHNQ9A0i/Ca1VGYZwNLnbbOKbwJjnpoSwT3BbWonDbnmzSUr90wetYast8XROVU1OOF1mEDUiB+YyO2u2rOmwjNtziFgM93BLRFtou1GUn8VQh6xbyFuwuwHk5aAD2ltLhjNS3AHTHu0bOmuK9DMARA==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
